sudo: required
services:
  - docker

before_install:
  - docker build -t rmykhailyshyn/learn-docker-react -f Dockerfile.dev .

language: generic 
script:
  - docker run -e CI=true rmykhailyshyn/learn-docker-react npm run test